services:
- type: web
  name: ğ‘³ğ’ğ’—ğ’† ğ‘©ğ’Šğ’•ğ’†
  runtime: docker
  repo: https://bitbucket.org/daredevil123/Love-Bite
  plan: free
  envVars:
  - key: SUDO
    sync: false
  - key: SESSION_ID
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
